### ISSUE TITLE
Deye Hybrid Inverters

### ISSUE THREAD

**Issue by cods4** [dasrecht/deye-firmware#10]
Any idea where to find the firmware for the hybrid inverters?
MCU1-SG-VerC3FC-CK.bin
This is an example filename, however unfortunately it doesn't come up when I try to pull it from here http://47.254.36.66/0_D0002_18/MCU1-SG-VerC3FC-CK.bin

**Comment by dasrecht** [comment]
Hi there, I don't own one of those devices. My best guess is that the `0_D0002_18` string would be different on the download server.

**Comment by cods4** [comment]
I have discovered the directory for the hybrid inverters. It is /0_5407_1/
And the latest firmware I have received is C362 which is named MCU1-SG-Ver0000-C362-CK.bin

**Comment by dasrecht** [comment]
Impressive :) do you have the full url handy i can add that to the repository

**Comment by cods4** [comment]
http://47.254.36.66/0_5407_1/MCU1-SG-Ver0000-C362-CK.bin

Replacing C362 with C363 or C364 also works. I haven't found anything else in that directory yet, and I haven't tried the newer firmwares (although it is tempting :) ).

**Comment by dasrecht** [comment]
Will add that in a seperate branch - do you have more information for which model this firmware works? :)

**Comment by cods4** [comment]
It seems to be the same file for the SG04LP1 series.
But I wouldn't be surprised if the same file does other inverters, I.e
3phase.

**Comment by clowrey** [comment]
> I have discovered the directory for the hybrid inverters. It is /0_5407_1/ And the latest firmware I have received is C362 which is named MCU1-SG-Ver0000-C362-CK.bin

Do you have any advice/info  on how you located the firmware directory? I am looking for the firmware for other versions of the hybrid inverters like the high voltage 25K model.. I am guessing each model type has its own folder etc.

**Comment by cods4** [comment]
There are some more firmwares for the hybrid inverters on my fork here https://github.com/cods4/deye-firmware/tree/main

The way I worked out the location was to install and configure squid on my router to log all unencrypted traffic, then ask Deye to upgrade the firmware on your router and squid should tell you the address your inverter is downloading the firmware from.
