### ISSUE TITLE
new version

### ISSUE THREAD

**Issue by basti122303** [dasrecht/deye-firmware#15]
http://47.254.36.66/0_D0002_18/MW3_16U_5406_2.30.bin
http://47.254.36.66/0_D0002_18/MW3_16U_5406_2.31.bin

please tag them

**Comment by dasrecht** [comment]
Added - Thanks for the information - where did you discover the new version?

**Comment by dasrecht** [comment]
Those versions seem to be connected to the new NA relais - which somehow the Inverter communicates with the Relais, as far as i was able to gather from a quick search

**Comment by basti122303** [comment]
> Added - Thanks for the information - where did you discover the new version?

I was searching for 2.27 to connect the NA relais.
2.27 seems not available anymore. So I just try to download some other version numbers form https://47.254.36.66/
In short, try and error.

**Comment by basti122303** [comment]
I loop from 2.31 to 2.99 and found an other one.
http://47.254.36.66/0_D0002_18/MW3_16U_5406_2.32.bin
`for i in {0..99} ; do wget http://47.254.36.66/0_D0002_18/MW3_16U_5406_2.$i.bin ; done`

perhaps be can do this by cron or somethink else.

**Comment by dasrecht** [comment]
Good point - i've added a simple script and the found versions :)

**Comment by dasrecht** [comment]
Ok i went a bit overboard and we have a ton of ne versions. the 2.27+ versions are most likely the ones needed with the external Relais box - https://stadt-bremerhaven.de/bnetza-genehmigt-deyes-relais-loesung/ 

Interesting tough that 2.27 isn't available anymore - so my guess is that they just roll out versions until stuff breaks and then pull the version from autoupdate and ship a fixed one.

Changelogs would be such a great thing but then we would most likely see how much stuff might be just done haphazardly

**Comment by basti122303** [comment]
`for i in $(seq -f "%02g" 0 11); do echo $i; done`
maybe a better way to find versions like 2.04.
i will close issue for now.

**Comment by basti122303** [comment]
Firmware 2.32 brick my device. 
Same as here https://www.borncity.com/blog/2023/09/09/deye-wechselrichter-sun600g3-eu-230-nach-anschluss-des-relaisbox-defekt/

**Comment by dasrecht** [comment]
Interesting :D thanks for mentioning that.

I think we're clear enough that this repo just mirrors versions and does not take any warranty that this firmware might brick devices.

**Comment by thncode** [comment]
> I get it working again. See the link above (german). I short: Register 002B was set to 0002 so I reset this to 0001. I use https://github.com/s10l/deye-logger-at-cmd for that.
> 
> `./main -t 10.0.0.30:48899 -xmbw 002b0001020001` Change the IP for your needs

that helped me for the same troubles but has to be repeated each day? Or is there some "save" option?

**Comment by basti122303** [comment]
> that helped me for the same troubles but has to be repeated each day?
That's the problem. I hope the Relais will fix it.

**Comment by thncode** [comment]
Is it possible to downgrade the firmware?

**Comment by basti122303** [comment]
You can try it, it does not helped for me.
You will need a NA Relais, I think.

**Comment by harryboo** [comment]
@basti122303: Thanx for this....

I got it working too again. Is there a description of the register?

**Comment by harryboo** [comment]
Found a list with register description... ;-)
002B is the ON / OFF register

**Comment by vordenken** [comment]
> Interesting :D thanks for mentioning that.
> 
> I think we're clear enough that this repo just mirrors versions and does not take any warranty that this firmware might brick devices. Or would you remove the 2.32 release from the repository?

I think this version should be removed or at least tagged with a warning... I updated to it because I had a weird bug running an older firmware and now the device seems to be bricked.
