### ISSUE TITLE
Add link to german forum thread ?

### ISSUE THREAD

**Issue by jedie** [dasrecht/deye-firmware#4]
https://www.photovoltaikforum.com/thread/187077-achtung-wifi-sicherheit-der-deye-und-bosswerk-mi600-300-sowie-baugleiche-microwe/?postID=2859297 has a long, german discussion about the security issues with Deye and Bosswerk Microinverter.

The Problems with the current Firmware versions is in short here: https://www.photovoltaikforum.com/thread/187077-achtung-wifi-sicherheit-der-deye-und-bosswerk-mi600-300-sowie-baugleiche-microwe/?postID=3090714#post3090714

**Comment by jedie** [comment]
Think it's also a good idea to link to these projects:

- https://github.com/Hypfer/deye-microinverter-cloud-free
- https://github.com/kbialek/deye-inverter-mqtt
- https://github.com/s10l/deye-logger-at-cmd

**Comment by dasrecht** [comment]
Hi @jedie - Very good idea. I was even thinking of somehow constructing a few changelogs from what we know by the obvious changes. 

Deye seems really not to want to publish any changelogs, sadly (i've asked them via support) and others did the same. So I was wondering if Bosswerk somehow has more understanding of the matter and would be willing to publish those.

**Comment by dasrecht** [comment]
Moved the Changelog idea in to #6 - Thanks for the links and the help :)
