### ISSUE TITLE
Compile changelog from publicly known information

### ISSUE THREAD

**Issue by dasrecht** [dasrecht/deye-firmware#6]
As Deye seems not to be willing to publish changelogs of their Logger Firmware updates, we could start to compile with the information that's known, e.g. the password change or Wi-Fi bands changes that came in lately. 

Still wondering if Bosswerk has real changelogs because based on their [FAQ for the MW3_16U_5406_1.53](https://www.bosswerk.de/wp-content/uploads/2023/03/Bosswerk_mi300_600_FAQ_Firmware_Update.pdf) it does not look like it

> Ein offizielles Change-Log haben wir aktuell noch nicht. Die hauptsächliche Neuerung ist das
> Abwenden der Zugriffsmöglichkeiten durch Dritte. Hierzu ist das Passwort des Access Point
> neu einzurichten. 

Most likely I'll get in touch with them - A Distributor might be able to have a bit more influence over the decisions made at Deye

**Comment by qwert4712** [comment]
Hi Bastian,
Q regarding **offline** flashing the new FW:

Can the e.g.  "MW3_16U_5406_1.57_4418.bin  be applied only to the 600W model?
Or to a 800W and 1600W as well?

thx
BR Michael

**Comment by dasrecht** [comment]
That's a good question - I think it should be the same - but can't test that

I guess if you see the same versions running as are present already it should be fine - but no guarantees.

**Comment by jw2013** [comment]
@qwert4712 , Deye remotely updated my 800W inverter to MW3_16U_5406_1.57

**Comment by dasrecht** [comment]
Hi @qwert4712 - Hard to say - what I once did is mailing Deye Support with my Device SN, and they triggered the upgrade from there. Yes, scary stuff, but I guess that's what you get these days.

**Comment by dasrecht** [comment]
On the Topic of Public Changelogs there hasn't been an answer from neither the OEM nor the companies that sell rebranded devices. I'll close this for now and pick it up maybe if there's more movement on it.
