### ISSUE TITLE
Tag version with release number

### ISSUE THREAD

**Issue by basti122303** [dasrecht/deye-firmware#8]
Hello,
would it be possible to label new versions (and maybe existing ones) with the release number?
This is how we can query the Github API for new versions.

Background:

My Deye inverter is completely disconnected from the internet so I would check for new firmware versions through Icinga or similar.
I'm ok with the delay between the official release and your release here on github.

Best regards

**Comment by dasrecht** [comment]
Would need to check if that's easily achievable - my goal was initially to only have a mirror somehow. If there are more people wanting this i could setup a pipeline that tags releases

**Comment by dasrecht** [comment]
I'll close this for now - There seems not to be any additional demand for it

**Comment by HeikoSchlittermann** [comment]
Hi, I stumbled over this issue, actually closed, but maybe worth to be re-opened. 
I'm about to setup a simple script for "release monitoring" if the deye firmware. This script would be simpler and more safe if releases would be tagged as such.

Simply following the default branch and considering the latest commit as stable is a way fragile.

What do you (@dasrecht) think? I'm not sure that you need to setup complicated CI pipelines to achive this.

**Comment by dasrecht** [comment]
Hi there :)

We can do this - the main issue I see is that, currently, this is only maintained on a best-effort basis, so if someone discovers a new version and creates a pull request, that gets merged in. But it's by no means automated :) I could automate a version tag/release when merging things if that's good enough. 

We could implement https://github.com/mikepenz/release-changelog-builder-action, for example, that would cut a new release once a semantic version tag is done. 

This will follow a separate versioning scheme, tough as we have firmware of different models there.

**Comment by dasrecht** [comment]
I'll close this for now, as this is more a research project rather than an official update repository. 

If there is someone that really wants release tagging and figuring that out - happy to add this person as a contributor.

**Comment by basti122303** [comment]
I will give them a try
