### ISSUE TITLE
File for 800w Version

### ISSUE THREAD

**Issue by stilicrafter** [dasrecht/deye-firmware#9]
hi,
do you also have the Files for the Deye SUN800G3-EU-230?

Currently i have this version. 

![image](https://user-images.githubusercontent.com/22886797/236851275-adf99cf7-780e-4a1f-9b00-8cecb2c15a28.png)

**Comment by aiomaster** [comment]
Just use the normal firmware. It works for all versions.
Tested this firmware https://github.com/dasrecht/deye-firmware/blob/main/0_D0002_18/MW3_16U_5406_1.57.bin on the same model as yours and it is working.

**Comment by stilicrafter** [comment]
Hi,
are you shure? Not that the 800w is after the update limited to 600w?

**Comment by dasrecht** [comment]
The firmware only affects the logger part of the Device and not the Microinverter itself. So you should be fine

**Comment by stilicrafter** [comment]
I ll try and let you know

**Comment by vArNi0101** [comment]
Has anyone already tried version 1.57PT? 

Yesterday my new SUN800G3 has made automatic update from 1.47 to 1.53

**Comment by stilicrafter** [comment]
Could an update affect the inverter?
Like not detecting 230V reliable?

**Comment by dasrecht** [comment]
Should not, there were comments in the forum where with some versions, the inverter didn't come online correctly. Those firmware are only targeting the logger part and not the electrical part, as far as we know so far.

**Comment by stilicrafter** [comment]
But no one else had strange behaviour after upgrade, right? 
![image](https://github.com/dasrecht/deye-firmware/assets/22886797/43cdec13-688f-4a72-8c48-c85ba65bb7e1)

**Comment by dasrecht** [comment]
Hi there, no issues with my device running on 1.57

<img width="1322" alt="image" src="https://github.com/dasrecht/deye-firmware/assets/391732/da8611b1-749d-43bd-98e8-4ab857aa7e5d">
